// src/app/experience/experience.component.ts
import { HttpClient } from '@angular/common/http';
import { Component, OnInit } from '@angular/core';

export class Exp {
  /**
   *
   */
  constructor() {
  }

  id!: number
  location!: string
  date!: string
  title!: string
  description!: string
  technologies!: string
}

@Component({
  selector: 'app-experience',
  templateUrl: './experience.component.html',
  styleUrls: ['./experience.component.css']
})
export class ExperienceComponent implements OnInit {

  experiences: any = []
  constructor(private httpClient: HttpClient) { }

  ngOnInit(): void {
    this.httpClient.get("../../assets/experiences.json").subscribe(data => {
      this.experiences = data;
    }
    )

    console.log(this.experiences)
  }
}

<div class="container" id="experience">
    <div class="row">

        <div class="col-sm-8 col-sm-offset-2 section-container-spacer">
            <div class="text-center">
                <h1 class="h2">03 : Experience</h1>

            </div>
            <div style="border-left: 2px solid white;">
                <ul class="timeline">
                    <li class="event" style="margin-bottom: 4em;" *ngFor="let exp of experiences">
                        <h3>{{exp["title"]}}</h3>
                        <h3>{{exp["location"]}}</h3>
                        <h4>{{exp["date"]}}</h4>
                        <div class="container" *ngFor="let desc of exp['description']">
                            <span>{{desc}}</span><br>
                        </div>
                        <h5 style="display: flex;align-items: center;" *ngIf="exp['technologies']!=[]">Technologies
                            <div style="display: flex; flex-wrap: wrap;" *ngFor="let tech of exp['technologies']">
                                <ul>
                                    <span class="fa-icon-white" style="font-size: 30px;">
                                        <i *ngIf="tech=='database'" class="fa-solid fa-{{tech}}"></i>
                                        <i *ngIf="tech!='database'" class="fa-brands fa-{{tech}}"></i>
                                    </span>
                                </ul>
                            </div>
                        </h5>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

// src/components/Experience.tsx
"use client";

import { faCalendarAlt } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { useEffect, useState } from "react";

interface Experience {
	id: number;
	location: string;
	title: string;
	date: string;
	description: string[];
	technologies: string[];
}

export default function Experience() {
	const [experiences, setExperiences] = useState<Experience[]>([]);

	useEffect(() => {
		fetch("/assets/data/experiences.json")
			.then((response) => response.json())
			.then((data) => setExperiences(data.reverse()))
			.catch((error) =>
				console.error("Error loading experiences:", error),
			);
	}, []);

	return (
		<div className="container" id="experience">
			<div className="row">
				<div
					className="col-xs-12 section-container-spacer"
					style={{ maxWidth: "800px", margin: "0 auto" }}
				>
					<div className="text-center">
						<h2>Experience</h2>
					</div>
					<div
						style={{
							borderLeft: "2px solid white",
							paddingLeft: "20px",
							marginTop: "40px",
						}}
					>
						<ul className="timeline">
							{experiences.map((exp) => (
								<li key={exp.id}>
									<h5>
										<FontAwesomeIcon icon={faCalendarAlt} />
										{exp.date}
									</h5>
									<div>
										<h3>{exp.location}</h3>
									</div>
									<h4 className="underline">{exp.title}</h4>
									{exp.description.map((desc, index) => (
										<div key={index} className="text-lg">
											<span> - {desc}</span>
										</div>
									))}
									{exp.technologies &&
										exp.technologies.length > 0 && (
											<div className="text-md font-mono flex gap-1 text-orange-300">
												{exp.technologies && (
													<p>
														import {""}
														{exp.technologies.map(
															(tech, index) => (
																<span
																	key={index}
																>
																	{tech}
																	{index !=
																	exp
																		.technologies
																		.length -
																		1
																		? ","
																		: " "}
																</span>
															),
														)}
													</p>
												)}
											</div>
										)}
								</li>
							))}
						</ul>
					</div>
				</div>
			</div>
		</div>
	);
}
